# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showFileText = QtWidgets.QLineEdit(self.centralwidget)
        self.showFileText.setReadOnly(True)
        self.showFileText.setObjectName("showFileText")
        self.horizontalLayout.addWidget(self.showFileText)
        self.selectFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout.addWidget(self.selectFileButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.showInputText = QtWidgets.QTextEdit(self.centralwidget)
        self.showInputText.setObjectName("showInputText")
        self.verticalLayout.addWidget(self.showInputText)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.outputButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputButton.sizePolicy().hasHeightForWidth())
        self.outputButton.setSizePolicy(sizePolicy)
        self.outputButton.setObjectName("outputButton")
        self.horizontalLayout_2.addWidget(self.outputButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.showOutputText = QtWidgets.QTextBrowser(self.centralwidget)
        self.showOutputText.setObjectName("showOutputText")
        self.verticalLayout.addWidget(self.showOutputText)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.allowHeadButton = QtWidgets.QCheckBox(self.centralwidget)
        self.allowHeadButton.setObjectName("allowHeadButton")
        self.horizontalLayout_4.addWidget(self.allowHeadButton)
        self.headText = QtWidgets.QLineEdit(self.centralwidget)
        self.headText.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headText.sizePolicy().hasHeightForWidth())
        self.headText.setSizePolicy(sizePolicy)
        self.headText.setMaximumSize(QtCore.QSize(30, 16777215))
        self.headText.setMaxLength(1)
        self.headText.setObjectName("headText")
        self.horizontalLayout_4.addWidget(self.headText, 0, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.allowTailButton = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allowTailButton.sizePolicy().hasHeightForWidth())
        self.allowTailButton.setSizePolicy(sizePolicy)
        self.allowTailButton.setObjectName("allowTailButton")
        self.horizontalLayout_5.addWidget(self.allowTailButton)
        self.tailText = QtWidgets.QLineEdit(self.centralwidget)
        self.tailText.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tailText.sizePolicy().hasHeightForWidth())
        self.tailText.setSizePolicy(sizePolicy)
        self.tailText.setMaximumSize(QtCore.QSize(30, 16777215))
        self.tailText.setMaxLength(1)
        self.tailText.setObjectName("tailText")
        self.horizontalLayout_5.addWidget(self.tailText, 0, QtCore.Qt.AlignRight)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.allowRejectButton = QtWidgets.QCheckBox(self.centralwidget)
        self.allowRejectButton.setObjectName("allowRejectButton")
        self.horizontalLayout_3.addWidget(self.allowRejectButton)
        self.rejectText = QtWidgets.QLineEdit(self.centralwidget)
        self.rejectText.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rejectText.sizePolicy().hasHeightForWidth())
        self.rejectText.setSizePolicy(sizePolicy)
        self.rejectText.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rejectText.setMaxLength(1)
        self.rejectText.setObjectName("rejectText")
        self.horizontalLayout_3.addWidget(self.rejectText, 0, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.allowCircleButton = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allowCircleButton.sizePolicy().hasHeightForWidth())
        self.allowCircleButton.setSizePolicy(sizePolicy)
        self.allowCircleButton.setObjectName("allowCircleButton")
        self.verticalLayout_2.addWidget(self.allowCircleButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.allButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton.sizePolicy().hasHeightForWidth())
        self.allButton.setSizePolicy(sizePolicy)
        self.allButton.setObjectName("allButton")
        self.verticalLayout_4.addWidget(self.allButton)
        self.charButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charButton.sizePolicy().hasHeightForWidth())
        self.charButton.setSizePolicy(sizePolicy)
        self.charButton.setObjectName("charButton")
        self.verticalLayout_4.addWidget(self.charButton)
        self.wordButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordButton.sizePolicy().hasHeightForWidth())
        self.wordButton.setSizePolicy(sizePolicy)
        self.wordButton.setObjectName("wordButton")
        self.verticalLayout_4.addWidget(self.wordButton, 0, QtCore.Qt.AlignTop)
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setText("")
        self.timeLabel.setObjectName("timeLabel")
        self.verticalLayout_4.addWidget(self.timeLabel, 0, QtCore.Qt.AlignVCenter)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectFileButton.setText(_translate("MainWindow", "选择文件"))
        self.label.setText(_translate("MainWindow", "输入内容："))
        self.label_2.setText(_translate("MainWindow", "输出内容："))
        self.outputButton.setText(_translate("MainWindow", "导出"))
        self.allowHeadButton.setText(_translate("MainWindow", "以"))
        self.label_4.setText(_translate("MainWindow", "开头"))
        self.allowTailButton.setText(_translate("MainWindow", "以"))
        self.label_5.setText(_translate("MainWindow", "开头"))
        self.allowRejectButton.setText(_translate("MainWindow", "禁止"))
        self.label_3.setText(_translate("MainWindow", "开头"))
        self.allowCircleButton.setText(_translate("MainWindow", "允许单词环"))
        self.allButton.setText(_translate("MainWindow", "所有单词链"))
        self.charButton.setText(_translate("MainWindow", "最多字母链"))
        self.wordButton.setText(_translate("MainWindow", "最长单词链"))
